#!/bin/bash

directories_list=(
	background/
	models/
)

for directory in ${directories_list[@]}
do
	for image in $(find "${directory}" -type f -iname "*.png")
	do
		optipng -o5 "${image}"
	done
done
