#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

USER_HOME="${HOME}"

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		if [ -z "${SUDO:-$HOME}" ]
		then
			SUDO_HOME=/root
		else
			SUDO_HOME="${SUDO:-$HOME}"
		fi

		USER="${SUDO_USER}"
		USER_HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${USER_HOME}"/.local/bin ]
	then
		mkdir -p "${USER_HOME}"/.local/bin/frobulator
	fi

	curl -s -L get.frbltr.app > "${USER_HOME}"/.local/bin/frobulator

	chmod +x "${USER_HOME}"/.local/bin/frobulator
fi

. "${USER_HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="11-30-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << MODEL-DRAWER-HEADER -> "modules/drawer.html"
<!-- scripts -->

<script src="/javascript/drawer.js" type="text/javascript"></script>

<script src="/javascript/year.js" type="text/javascript"></script>

<!-- drawer -->

<div class="drawer">

	<div class="drawer-button cursor-cell">

		<div class="icon icon-64 logo-grey"></div>

	</div>

	<div class="grid grid-column grid-stretch">

		<!-- legend -->

		<div class="list section notice">

			<div class="grid grid-column grid-middle">

				<div class="grid-cell text-bold text-center">

					// NOTICE</br>
					</br>

				</div>

				<div class="grid-cell text-center">

					INSTRUCTIONS ARE MADE AVAILABLE PROGRESSIVELY:</br>
					</br>
					PURCHASING AN INSTRUCTION SET PRIORITIZES AVAILABILITY FOR THAT MODEL!</br>
					</br>

				</div>

				<div class="grid-cell text-bold text-center">

					THANK YOU FOR YOUR SUPPORT! <3 //</br>

				</div>

			</div>

		</div>

		<!-- instructions available -->

		<div class="list section available">

			<div class="grid grid-row grid-middle">

				<div class="grid">

					<div class="icon icon-flex icon-center logo-green"></div>

				</div>

				<div class="grid-cell text-center">

					AVAILABLE

				</div>

			</div>

		</div>

		<!-- instructions progress -->

		<div class="list section progress">

			<div class="grid grid-row grid-middle">

				<div class="grid">

					<div class="icon icon-flex icon-center logo-orange"></div>

				</div>

				<div class="grid-cell text-center">

					IN PROGRESS

				</div>

			</div>

		</div>

		<!-- models -->

MODEL-DRAWER-HEADER

# values

extensions_list=(
	png
)

for extension in ${extensions_list[@]}
do
	count=1

	# shuffle models directories list:
	# generates random showcase of all models on each update

	for models_list in $(find models/ -type f -iname flat."${extension}" | sort)
	do
		IFS='/' read -r -a path <<< $(echo "$models_list")

		# /models/model-type/model/renders/render-type/render.${extension}

		# "${path[0]}" /models
		# "${path[1]}" /model-category
		# "${path[2]}" /model
		# "${path[3]}" /renders

		# render types:

		# "${path[4]}" /outine
		# "${path[4]}" /flat
		# "${path[4]}" /thumbnail

		# "${path[5]}" /render.extension

		model_category=$(cat ${path[0]}/${path[1]}/title)

		model_title=$(cat ${path[0]}/${path[1]}/${path[2]}/title)

		model_title_string=$(echo ${model_title//\<\/\br\>/})

		model_paypal=${path[0]}/${path[1]}/${path[2]}/paypal

		model_paypal_id=$(cat ${path[0]}/${path[1]}/${path[2]}/paypal)

		model_pieces=${path[0]}/${path[1]}/${path[2]}/pieces

		model_pieces_count=$(cat ${path[0]}/${path[1]}/${path[2]}/pieces)

		model_instructions=${path[0]}/${path[1]}/${path[2]}/instructions

		model_instructions_price=$(cat ${path[0]}/${path[1]}/${path[2]}/price)

# generate model drawer entries

if [ ! -f models/"${path[1]}"/todo ]
then

cat << MODEL-DRAWER-CONTENT ->> "modules/drawer.html"
		<div class="list section">

			<div class="grid grid-column grid-stretch">

				<div class="grid-cell category">

					${model_category}

				</div>

				<a class="button" href="/models/${path[1]}/${path[2]}/">

					<div class="grid grid-row grid-middle">

						<div class="grid-cell-start">

							<div class="icon icon-flex icon-center logo-green"></div>

						</div>

						<div class="grid-cell text-center">

							<img src="/${path[0]}/${path[1]}/${path[2]}/${path[3]}/thumbnail/thumbnail.png" />

						</div>

					</div>


					<div class="grid grid-column grid-middle">

						<div class="grid-cell text-center">

							${model_title}

						</div>

						<div class="grid-cell text-center">

							${model_pieces_count} PIECES

						</div>

					</div>

				</a>

			</div>

		</div>

MODEL-DRAWER-CONTENT

else

cat << MODEL-DRAWER-CONTENT ->> "modules/drawer.html"
		<div class="list section">

			<div class="grid grid-column grid-stretch">

				<div class="grid-cell category">

					${model_category}

				</div>

				<a class="button" href="/models/${path[1]}/${path[2]}/">

					<div class="grid grid-row grid-middle">

						<div class="grid-cell-start">

							<div class="icon icon-flex icon-center logo-orange"></div>

						</div>

						<div class="grid-cell text-center">

							<img src="/${path[0]}/${path[1]}/${path[2]}/${path[3]}/thumbnail/thumbnail.png" />

						</div>

					</div>


					<div class="grid grid-column grid-middle">

						<div class="grid-cell text-center">

							${model_title}

						</div>

						<div class="grid-cell text-center">

							${model_pieces_count} PIECES

						</div>

					</div>

				</a>

			</div>

		</div>

MODEL-DRAWER-CONTENT

fi

	((count++))

	done
done

# generate footer

cat << MODEL-DRAWER-FOOTER ->> "modules/drawer.html"
		<!-- copyright -->

		<div class="list section copyright">

			<div class="grid grid-column grid-middle">

				<div class="grid-cell">

					<div class="avatar avatar-64 avatar-center" href=""></div>

				</div>

			</div>

			<div class="grid grid-column grid-middle">

				<div class="grid-cell text-center">

					Version // ${stamp}</br>
					Lego // Linux - Where Lego meets Linux</br>
					N Λ T H Λ N E L - ©  <text id="year"></text>

				</div>

			</div>

		</div>

	</div>

</div>

MODEL-DRAWER-FOOTER

frobulator.inf "Parsed model entries" "[ ${count} ]"
echo

frobulator.scs "Models drawer" "[ Done ]"
echo
