#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="01-14-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

local_models_directory=/media/internal/Lego/models
server_models_directory="${PWD}"/models
server_backgrounds_directory="${PWD}"/background
server_javascript_directory="${PWD}"/javascript

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# prepare update

list+=(
	"${server_models_directory}"
)

for directory in ${list[@]}
do
	rm -rf "${directory}" ]

	frobulator.directory "${directory}"
done

list=()

# pull /////////////////////////////////////////////////////////////////////////

rsync							\
	--archive					\
	--quiet						\
	--recursive					\
	--exclude='*.ldr'			\
	--exclude='*.mpd'			\
	--exclude='*.pdf'			\
	--exclude="instructions"	\
	--exclude="configuration"	\
	--exclude='LPub3D'			\
								"${local_models_directory}"/* "${server_models_directory}"

frobulator.scs "Copy" "[ Done ]"
echo
