#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
    if [[ -z $(command -v curl) ]]
    then
        yes | apt-get install curl
    fi

    curl -s -L get.frbltr.app > /usr/bin/frobulator

    chmod +x /usr/bin/frobulator
fi

. /usr/bin/frobulator

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER}"
	HOME=/home/"${USER}"
fi

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="04-28-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

local_models_directory=/media/internal/Lego/models
server_models_directory="${PWD}"/models
server_backgrounds_directory="${PWD}"/background
server_javascript_directory="${PWD}"/javascript

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# background ///////////////////////////////////////////////////////////////////

# prepare update

directories_list=(
	"${server_backgrounds_directory}"
)

for directory in ${directories_list[@]}
do
	rm -rf "${directory}" ]

	mkdir -p "${directory}"
done

# values

extensions_list=(
	png
)

# copy images

frobulator.fwd "Copying..."
echo

for extension in ${extensions_list[@]}
do
	# copy flat renders into background directory

	count=0

	for background in $(find ${local_models_directory} -type f -iname flat."${extension}")
	do
		pad_count=$(printf "%03d" "${count}")

	    rsync					\
			--archive			\
			--quiet				\
			--recursive			\
								"${background}" "${server_backgrounds_directory}"/background-"${pad_count}"."${extension}"

	    ((count++))

	done

	# update random background generator with new file count

	frobulator.inf "Updating" "[ background ]"
	echo

	sed													\
		-i												\
		-e "s/var count = .*/var count = ${count};/g"	\
														"${server_javascript_directory}"/background.js
done

frobulator.inf "Parsed model entries" "[ ${count} ]"
echo

frobulator.scs "Copy" "[ Done ]"
echo
