#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="08-30-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

models_directory="${PWD}"/models

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# values

extensions_list+=(
	dae
)

for extension in ${extensions_list[@]}
do
	count=1

	models_list=( $(find ${models_directory} -type f -iname "*.${extension}" ! -iname "*instructions*") )

	# set IFS

	IFS=$'\n'

	for model_path in ${models_list[@]}
	do
		model_path=$(echo "${model_path}" | cut -d '/' -f6-)

		# get model file name from path

		model_file="${model_path##*/}"

		# strip extension from model file name

		model_name="${model_file%.*}"

		# use model directory as root

		model_directory="${model_path%/*/*}"

		# define model output directories

		export_directory="${render_directory}"/exports

		render_directory="${model_directory}"/renders

		flat_directory="${render_directory}"/flat

		thumbnail_directory="${render_directory}"/thumbnail

		# define model specific directories

		model_category=$(cat "${model_directory%/*}"/title)

		model_title=$(cat "${model_directory}"/title)

		model_title_string=$(echo ${model_title//\<\/\br\>/})

		model_paypal="${model_directory}"/paypal

		model_paypal_id=$(cat "${model_paypal}")

		model_pieces="${model_directory}"/pieces

		model_pieces_count=$(cat "${model_pieces}")

		model_instructions="${model_directory}"/instructions

		model_price="${model_directory}"/price

		model_instructions_price=$(cat "${model_price}")

		# generate 3d model page

		if [[ "${model_paypal_id}" = "" ]]
		then
			model_paypal_id="NOT YET AVAILABLE FOR PURCHASE"
		fi

cat << 3D-MODEL-PAGE-HEADER -> "${model_directory}/index.html"
<!DOCTYPE html>

<html>

	<head>

		<!-- css -->

		<link rel="stylesheet" href="/css/css.css" type="text/css" />

		<!-- libraries -->

		<script src="/javascript/jquery-3.7.0.min.js" type="text/javascript"></script>

		<!-- scripts -->

		<script src="/javascript/modules.js" type="text/javascript"></script>

	</head>

3D-MODEL-PAGE-HEADER

cat << 3D-MODEL-PAGE-VIEWER ->> "${model_directory}/index.html"
	<body>

		<div id="drawer">

		</div>

		<!-- interactive render container -->

		<canvas id="canvas" class="cursor-move"></canvas>

		<!-- BEGIN 3D VIEWER -->

		<script type="module">

			import * as THREE from '/javascript/three/build/three.js';

			import { ColladaLoader } from '/javascript/three/modules/loaders/ColladaLoader.js';

			import { OrbitControls } from '/javascript/three/modules/controls/OrbitControls.js';

			function init() {

				// canvas

				var canvas = document.querySelector('#canvas');

				// renderer

				var renderer = new THREE.WebGLRenderer( { canvas, antialias: true, alpha: true } );

				renderer.setClearColor( 0x000000, 0 );
				renderer.setPixelRatio( window.devicePixelRatio );
				renderer.shadowMap.enabled = true;
				renderer.shadowMap.type = THREE.PCFSoftShadowMap;

				// camera

				var camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 5000);

				camera.position.set( 45, 30, 45 );
				camera.lookAt( 0, 0, 0 );

				// scene

				var scene = new THREE.Scene();

				// controls

				var controls = new OrbitControls( camera, renderer.domElement );

				controls = new OrbitControls( camera, renderer.domElement );

				controls.keys = {
					LEFT: 'ArrowLeft',
					UP: 'ArrowUp',
					RIGHT: 'ArrowRight',
					BOTTOM: 'ArrowDown'
				}

				controls.mouseButtons = {
					LEFT: THREE.MOUSE.ROTATE,
					MIDDLE: THREE.MOUSE.PAN,
					RIGHT: THREE.MOUSE.ROTATE

					// RIGHT: THREE.MOUSE.DOLLY
				}

				controls.screenSpacePanning = true;
				controls.enablePan = true;
				controls.target.set( 0, 0, 0 );
				controls.minDistance = 0.5;
				controls.maxDistance = 1.0;

				controls.update();

				// lights

				var ambientLight = new THREE.AmbientLight( 0xffffff, 1 );

				// scene.add( ambientLight );

				// directional lights

				var dirLight = new THREE.DirectionalLight( 0xffffff, 0.125 );

				dirLight.position.set( 0, 10, 10 );
				dirLight.castShadow = true;
				dirLight.shadow.mapSize.width = 512;
				dirLight.shadow.mapSize.height = 512;
				dirLight.shadow.camera.near = 512;
				dirLight.shadow.camera.far = 512;

				scene.add( dirLight );

				// hemispherical lights

				var hemiLight = new THREE.HemisphereLight( 0xffffff, 0xcccccc, 0.75 );

				hemiLight.position.set( 0, 10, 0 );
				// hemiLight.castShadow = true;

				scene.add( hemiLight );

				// point lights

				var pointLight = new THREE.PointLight( 0xffffff, 0.125, 0, 2 );

				pointLight.position.set(0, 10, 10);
				pointLight.castShadow = true;
				pointLight.shadow.mapSize.width = 512;
				pointLight.shadow.mapSize.height = 512;
				pointLight.shadow.camera.near = 512;
				pointLight.shadow.camera.far = 512;

				// scene.add( pointLight );

				// loader

				var loader = new ColladaLoader();

				var model = loader.load( '/${model_path}', function ( collada ) {

					var collada = collada.scene;

					// load model

					scene.add( collada );

					// helpers

					// lights

					// scene.add( new THREE.DirectionalLightHelper( dirLight, 0 , 0xaaaaaa ) );
					// scene.add( new THREE.HemisphereLightHelper( hemiLight, 5 , 0xaaaaaa ) );
					// scene.add( new THREE.PointLightHelper( pointLight, 0 , 0xaaaaaa ) );

					// bounding box

					var boundingboxHelper = new THREE.BoxHelper( model, 0xaaaaaa );

					// scene.add( boundingboxHelper );

					// grids

					// orthogonal grid

					const orthogonalGrid = new THREE.GridHelper( 0.5, 16, 0xaaaaaa, 0xaaaaaa );

					orthogonalGrid.position.y = 0;
					orthogonalGrid.position.x = 0;

					// scene.add( orthogonalGrid );

					// polar grid

					const polarGridHelper = new THREE.PolarGridHelper( 0.5, 32, 32, 32, 0xaaaaaa, 0xaaaaaa );

					polarGridHelper.position.y = 0;
					polarGridHelper.position.x = 0;

					// scene.add( polarGridHelper );


				} );

				// resize

				function resize () {

					const canvas = renderer.domElement;

					const width = canvas.clientWidth;
					const height = canvas.clientWidth;

					const resizeNeeded = canvas.width !== width || canvas.height !== height;

					if ( resizeNeeded ) {

						renderer.setSize ( width, height, false );
					}

					return resizeNeeded;
				}

				function render() {

					if ( resize ( renderer ) ) {

						const canvas = renderer.domElement;
						camera.aspect = canvas.clientWidth / canvas.clientHeight;
						camera.updateProjectionMatrix();

					}

					renderer.render( scene, camera );
					requestAnimationFrame( render );
				}

				requestAnimationFrame( render );

			}

			init();

		</script>

		<!-- END 3D VIEWER -->

3D-MODEL-PAGE-VIEWER

if [ -f "${model_paypal}" ]
then

cat << 3D-MODEL-PAYPAL ->> "${model_directory}/index.html"
		<!-- paypal -->

			<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=${model_paypal_id}">

				<div class="flex flex-row flex-middle flex-around paypal">

					<div class="flex-cell text-bold">

						Purchase

					</div>

					<div class="flex-cell">

						<div class="icon icon-64 logo-paypal"></div>

					</div>

				</div>

			</a>

3D-MODEL-PAYPAL

fi

cat << 3D-MODEL-PRODUCT ->> "${model_directory}/index.html"

		<div class="paypal-id">

			[ ID // ${model_paypal_id} ] - US\$ ${model_instructions_price}

			<div class="product">

				<div class="hide product-identifier">

					${model_paypal_id}

				</div>

				<div class="hide product-name">

					${path[2]}

				</div>

			</div>

		</div>

3D-MODEL-PRODUCT

cat << 3D-MODEL-PAGE-COLORS ->> "${model_directory}/index.html"
		<div id="colors">

		</div>

3D-MODEL-PAGE-COLORS

cat << 3D-MODEL-PAGE-FOOTER ->> "${model_directory}/index.html"
		<div id="footer" class="section">

		</div>

	</body>

</html>

3D-MODEL-PAGE-FOOTER

	((count++))

	done
done

frobulator.inf "Models" "[ ${count} ]"
echo

frobulator.scs "Done" "[ Viewer ]"
echo
