#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

USER_HOME="${HOME}"

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		if [ -z "${SUDO:-$HOME}" ]
		then
			SUDO_HOME=/root
		else
			SUDO_HOME="${SUDO:-$HOME}"
		fi

		USER="${SUDO_USER}"
		USER_HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${USER_HOME}"/.local/bin ]
	then
		mkdir -p "${USER_HOME}"/.local/bin/frobulator
	fi

	curl -s -L get.frbltr.app > "${USER_HOME}"/.local/bin/frobulator

	chmod +x "${USER_HOME}"/.local/bin/frobulator
fi

. "${USER_HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="11-30-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo
# values

extensions_list=(
	png
)

for extension in ${extensions_list[@]}
do
	count=1

	# shuffle models directories list:
	# creates random showcase of all models on each update

	for models_list in $(find models/ -type f -iname flat."${extension}" | shuf)
	do
		IFS='/' read -r -a path <<< $(echo "$models_list")

		# /models/model-type/model/renders/flat/flat.${extension}

		# "${path[0]}" /models
		# "${path[1]}" /model-category
		# "${path[2]}" /model
		# "${path[3]}" /renders
		# "${path[4]}" /outine
		# "${path[5]}" /flat

		model_category=$(cat ${path[0]}/${path[1]}/title)

		model_title=$(cat ${path[0]}/${path[1]}/${path[2]}/title)

		model_title_string=$(echo ${model_title//\<\/\br\>/})

		model_paypal=${path[0]}/${path[1]}/${path[2]}/paypal

		model_paypal_id=$(cat ${path[0]}/${path[1]}/${path[2]}/paypal)

		model_pieces=${path[0]}/${path[1]}/${path[2]}/pieces

		model_pieces_count=$(cat ${path[0]}/${path[1]}/${path[2]}/pieces)

		model_instructions=${path[0]}/${path[1]}/${path[2]}/instructions

		model_instructions_price=$(cat ${path[0]}/${path[1]}/${path[2]}/price)

# generate 3d model page

cat << 3D-MODEL-PAGE-HEADER -> "models/${path[1]}/${path[2]}/index.html"
<!DOCTYPE html>

<html>

	<head>

		<!-- css -->

		<link rel="stylesheet" href="/css/css.css" type="text/css" />

		<!-- libraries -->

		<script src="/javascript/jquery-3.4.1.min.js" type="text/javascript"></script>

		<!-- scripts -->

		<script src="/javascript/modules.js" type="text/javascript"></script>

	</head>

3D-MODEL-PAGE-HEADER

cat << 3D-MODEL-PAGE-VIEWER ->> "models/${path[1]}/${path[2]}/index.html"
	<body>

		<div id="drawer">

		</div>

		<!-- interactive render container -->

		<canvas id="canvas" class="cursor-move"></canvas>

		<!-- BEGIN 3D VIEWER -->

		<script type="module">

			import * as THREE from '/build/three.module.js';

			import { ColladaLoader } from '/jsm/loaders/ColladaLoader.js';

			import { OrbitControls } from '/jsm/controls/OrbitControls.js';

			function init() {

				// canvas

				var canvas = document.querySelector('#canvas');

				// renderer

				var renderer = new THREE.WebGLRenderer( { canvas, antialias: true, alpha: true } );

				renderer.setClearColor( 0x000000, 0 );
				renderer.setPixelRatio( window.devicePixelRatio );
				renderer.shadowMap.enabled = true;
				renderer.shadowMap.type = THREE.PCFSoftShadowMap;

				// camera

				var camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 5000);

				camera.position.set( 45, 30, 45 );
				camera.lookAt( 0, 0, 0 );

				// scene

				var scene = new THREE.Scene();

				// controls

				var controls = new OrbitControls( camera, renderer.domElement );

				controls = new OrbitControls( camera, renderer.domElement );

				controls.keys = {
					LEFT: 'ArrowLeft',
					UP: 'ArrowUp',
					RIGHT: 'ArrowRight',
					BOTTOM: 'ArrowDown'
				}

				controls.mouseButtons = {
					LEFT: THREE.MOUSE.ROTATE,
					MIDDLE: THREE.MOUSE.PAN,
					RIGHT: THREE.MOUSE.ROTATE

					// RIGHT: THREE.MOUSE.DOLLY
				}

				controls.screenSpacePanning = true;
				controls.enablePan = true;
				controls.target.set( 0, 0, 0 );
				controls.minDistance = 0.5;
				controls.maxDistance = 1.0;

				controls.update();

				// lights

				var ambientLight = new THREE.AmbientLight( 0xffffff, 1 );

				// scene.add( ambientLight );

				// directional lights

				var dirLight = new THREE.DirectionalLight( 0xffffff, 0.125 );

				dirLight.position.set( 0, 10, 10 );
				dirLight.castShadow = true;
				dirLight.shadow.mapSize.width = 512;
				dirLight.shadow.mapSize.height = 512;
				dirLight.shadow.camera.near = 512;
				dirLight.shadow.camera.far = 512;

				scene.add( dirLight );

				// hemispherical lights

				var hemiLight = new THREE.HemisphereLight( 0xffffff, 0xcccccc, 0.75 );

				hemiLight.position.set( 0, 10, 0 );
				// hemiLight.castShadow = true;

				scene.add( hemiLight );

				// point lights

				var pointLight = new THREE.PointLight( 0xffffff, 0.125, 0, 2 );

				pointLight.position.set(0, 10, 10);
				pointLight.castShadow = true;
				pointLight.shadow.mapSize.width = 512;
				pointLight.shadow.mapSize.height = 512;
				pointLight.shadow.camera.near = 512;
				pointLight.shadow.camera.far = 512;

				// scene.add( pointLight );

				// loader

				var loader = new ColladaLoader();

				loader.load( '/${path[0]}/${path[1]}/${path[2]}/exports/${path[2]}.dae', function ( collada ) {

					var collada = collada.scene;

					// load model

					scene.add( collada );

					// helpers

					// lights

					// scene.add( new THREE.DirectionalLightHelper( dirLight, 0 , 0xaaaaaa ) );
					// scene.add( new THREE.HemisphereLightHelper( hemiLight, 5 , 0xaaaaaa ) );
					// scene.add( new THREE.PointLightHelper( pointLight, 0 , 0xaaaaaa ) );

					// bounding box

					var boundingboxHelper = new THREE.BoxHelper( model, 0xaaaaaa );

					// scene.add( boundingboxHelper );

					// grids

					// orthogonal grid

					const orthogonalGrid = new THREE.GridHelper( 0.5, 16, 0xaaaaaa, 0xaaaaaa );

					orthogonalGrid.position.y = 0;
					orthogonalGrid.position.x = 0;

					// scene.add( orthogonalGrid );

					// polar grid

					const polarGridHelper = new THREE.PolarGridHelper( 0.5, 32, 32, 32, 0xaaaaaa, 0xaaaaaa );

					polarGridHelper.position.y = 0;
					polarGridHelper.position.x = 0;

					// scene.add( polarGridHelper );


				} );

				// resize

				function resize () {

					const canvas = renderer.domElement;

					const width = canvas.clientWidth;
					const height = canvas.clientWidth;

					const resizeNeeded = canvas.width !== width || canvas.height !== height;

					if ( resizeNeeded ) {

						renderer.setSize ( width, height, false );
					}

					return resizeNeeded;
				}

				function render() {

					if ( resize ( renderer ) ) {

						const canvas = renderer.domElement;
						camera.aspect = canvas.clientWidth / canvas.clientHeight;
						camera.updateProjectionMatrix();

					}

					renderer.render( scene, camera );
					requestAnimationFrame( render );
				}

				requestAnimationFrame( render );

			}

			init();

		</script>

		<!-- END 3D VIEWER -->

3D-MODEL-PAGE-VIEWER

if [ -f "${model_paypal}" ]
then

cat << 3D-MODEL-PAYPAL ->> "models/${path[1]}/${path[2]}/index.html"
		<!-- paypal -->

			<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=${model_paypal_id}">

				<div class="paypal grid grid-column">

					<div class="grid-cell grid-cell-center">

						<div class="icon icon-64 logo-yellow"></div>

					</div>

					<div class="grid-cell grid-cell-center">

						\$${model_instructions_price} USD

					</div>

					<div class="grid-cell grid-cell-center">

						BUY NOW!

					</div>

				</div>

			</a>

3D-MODEL-PAYPAL

fi

cat << 3D-MODEL-PAGE-FOOTER ->> "models/${path[1]}/${path[2]}/index.html"
		<div id="footer" class="section">

		</div>

	</body>

</html>

3D-MODEL-PAGE-FOOTER

	((count++))

	done
done

frobulator.inf "Parsed model entries" "[ ${count} ]"
echo

frobulator.scs "3D model pages" "[ Done ]"
echo
