#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	curl -s -L get.frbltr.app > /usr/bin/frobulator
fi

. /usr/bin/frobulator

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER}"
	HOME=/home/"${USER}"
fi

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="08-16-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

local_content_directory="${PWD}"/
local_server_directory=/var/www/html/legolinux

# defaults /////////////////////////////////////////////////////////////////////

list=(
	apache2
)

frobulator.require ${list[@]}

# functions ////////////////////////////////////////////////////////////////////

# generate server configuration

cat <<- FILE > /etc/apache2/sites-enabled/legolinux.conf
<VirtualHost *:80>
        ServerAdmin     nathanel.titane@gmail.com
        ServerName      legolinux
        ServerAlias     dev.legolinux.com
        DocumentRoot    /var/www/html/legolinux/
        ErrorLog        ${APACHE_LOG_DIR}/legolinux.error.log
        CustomLog       ${APACHE_LOG_DIR}/legolinux.access.log combined
</VirtualHost>
FILE

# reload service

service apache2 reload

# enable virtual host configuration distribution

a2ensite legolinux.conf

# configure hosts redirection

cat <<- FILE >> /etc/hosts
127.0.0.1       dev.legolinux.com
FILE

# generate local server directory

directories_list=(
	/var/www/html/legolinux
)

for directory in ${directories_list[@]}
do
	mkdir -p "${directory}"

	chmod -R 777 "${directory}"
done

# pull /////////////////////////////////////////////////////////////////////////

rsync					\
	--archive			\
	--quiet				\
	--recursive			\
	--exclude='*.ldr'	\
	--exclude='*.mpd'	\
	--exclude='*.pdf'	\
						"${local_content_directory}"/* "${local_server_directory}"

frobulator.scs "Server" "[ Done ]"
echo
