#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="01-14-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

local_directory=/media/internal/Lego
local_models_directory="${local_directory}"/models

server_directory="${PWD}"
server_models_directory="${server_directory}"/models
server_backgrounds_directory="${server_directory}"/background
server_javascript_directory="${server_directory}"/javascript

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

# background ///////////////////////////////////////////////////////////////////

# prepare update

frobulator.directory "${server_directory}" background

# values

extensions_list+=(
	png
)

# copy images

frobulator.fwd "Copying..."
echo

for extension in ${extensions_list[@]}
do
	# copy flat renders into background directory

	counter=0

	# set IFS

	IFS=$'\n'

	# shuffle models directories list:
	# creates random showcase of all models on each update

	for background in $(find ${local_models_directory} -type f -iname flat."${extension}" | shuf)
	do
		pad_counter=$(printf "%03d" "${counter}")

		rsync				\
			--archive		\
			--quiet			\
			--recursive		\
							"${background}" "${server_background_directory}"/background-"${pad_counter}"."${extension}" > "${sink}" 2>&1

		((counter++))

	done

	# reset IFS

	IFS=''

	# update random background generator with new file count

	frobulator.inf "Updating" "[ background ]"
	echo

	sed													\
		-i												\
		-e "s/var count = .*/var count = ${counter};/g"	\
														"${server_javascript_directory}"/background.js
done

frobulator.inf "Models" "[ ${counter} ]"
echo

frobulator.scs "Done" "[ Background ]"
echo
