#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="01-04-2022"

# usage ///////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}" in
		-directory)
			directory="${2}"

			shift
		;;

		-a|--all)
			option="all"
		;;

		-e|--export)
			option="exports"
		;;

		-r|--render)
			option="renders"
		;;

		-m|--models)
			option="models"
		;;

		-b|--background)
			option="background"
		;;

		-n|--menu)
			option="menu"
		;;

		-d|--drawer)
			option="drawer"
		;;

		-v|--viewer)
			option="viewer"
		;;

		-h|--help)
			echo
			echo -e "Usage: ./${script} [EXTENSION] | [OPTION] [PARAMETER]"
			echo
			echo -e "Utility options:"
			echo
			echo -e "-directory        Specify directory to load models from."
			echo
			echo -e "-all              Full website framework and content update."
			echo
			echo -e "-exports          Models exports content update."
			echo -e "-renders          Models renders content update."
			echo -e "-background       Background content update."
			echo -e "-drawer           Drawer content update."
			echo -e "-menu             Models menu content update."
			echo -e "-models           Models content update."
			echo -e "-viewer           Models viewer content update."
			echo
			echo -e "'${script}'       [ Version ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ./${script} [EXTENSION] | [OPTION] [PARAMETER]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1

		;;

		esac

		shift
done

# clear ////////////////////////////////////////////////////////////////////////

frobulator.clear

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

upload () {
	git add *

	git commit		\
		--all		\
		--message='Models update'

	git push > /dev/null 2>&1
}

run () {
	for script in ${scripts_list[@]}
	do
		bash ./"${script}"
	done
}

option () {
	selection="${1}"

	if [[ -n "${#list[@]}" ]]
	then
		# ${2} - array

		list=(${@:3})
	else
		script="${3}"

		list=()

		list+=("${script}")
	fi

	if [[ "${option}" = "${selection}" ]]
	then
		"${script}"

		run

		upload &

		frobulator.progress "Updating" "[ ${selection} ]"
		echo
	fi
}

# requirements /////////////////////////////////////////////////////////////////

list=(
	git
	rsync
)

frobulator.assess ${list[@]}

list=()

# update ///////////////////////////////////////////////////////////////////////

# content

option all

if [[ "${option}" = "renders" ]]
then
	scripts_list+=(
		legolinux-renders
	)

	run

	upload &

	frobulator.progress "Updating renders..."
	echo
fi

if [[ "${option}" = "models" ]]
then
	scripts_list+=(
		legolinux-models
		legolinux-background
		legolinux-drawer
		legolinux-viewer
	)

	run

	upload &

	frobulator.progress "Updating models..."
	echo
fi

if [[ "${option}" = "pages" ]]
then
	upload &

	frobulator.progress "Updating pages..."
	echo
fi

frobulator.scs "Update" "[ Done ]"
echo
