#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="08-30-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

models_directory="${PWD}"/models
modules_directory="${PWD}"/modules

stamp=$(date +"%m-%d-%Y")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << MODEL-DRAWER-HEADER -> "${modules_directory}"/drawer.html
<!-- scripts -->

<script src="/javascript/drawer.js" type="text/javascript"></script>

<script src="/javascript/year.js" type="text/javascript"></script>

<div class="flex flex-row flex-middle flex-around drawer-button cursor-cell">

	<div id="drawer-button-label" class="flex-cell text-bold">

		Menu

	</div>

	<div id="drawer-button-icon" class="flex-cell">

		<div class="icon icon-64 logo-drawer"></div>

	</div>

</div>

<!-- drawer -->

<div class="drawer">

	<div class="flex flex-column flex-stretch">

		<!-- legend -->

		<div class="list section notice">

			<div class="flex flex-column flex-middle">

				<div class="flex-cell text-bold text-center">

					// NOTICE //</br>

					</br>

				</div>

				<div class="flex-cell text-center">

					INSTRUCTIONS ARE MADE AVAILABLE PROGRESSIVELY:</br>

					</br>

					PURCHASING AN INSTRUCTION SET PRIORITIZES AVAILABILITY FOR THAT MODEL!</br>

					</br>

					 YOU CAN <label for="modal-contact" class="modal-item contact cursor-pointer text-bold">// CONTACT //</label> US REGARDING ANY SPECIFIC MODEL, ANYTIME!</br>

					 </br>

				</div>

				<div class="flex-cell text-bold text-center">

					THANK YOU FOR YOUR SUPPORT!</br>

				</div>

			</div>

		</div>

		<!-- instructions available -->

		<div class="list section available">

			<div class="flex flex-row flex-middle">

				<div class="flex">

					<div class="icon icon-flex icon-center logo-green"></div>

				</div>

				<div class="flex-cell text-center">

					AVAILABLE

				</div>

			</div>

		</div>

		<!-- instructions progress -->

		<div class="list section progress">

			<div class="flex flex-row flex-middle">

				<div class="flex">

					<div class="icon icon-flex icon-center logo-orange"></div>

				</div>

				<div class="flex-cell text-center">

					IN PROGRESS

				</div>

			</div>

		</div>

		<!-- models -->

MODEL-DRAWER-HEADER

# values

extensions_list+=(
	dae
)

for extension in ${extensions_list[@]}
do
	count=1

	models_list=( $(find "${models_directory}" -type f -iname "*.${extension}" ! -iname "*instructions*" | sort) )

	# set IFS

	IFS=$'\n'

	for model_path in ${models_list[@]}
	do
		model_path=$(echo "${model_path}" | cut -d '/' -f6-)

		# get model file name from path

		model_file="${model_path##*/}"

		# strip extension from model file name

		model_name="${model_file%.*}"

		# use model directory as root

		model_directory="${model_path%/*/*}"

		# define model output directories

		export_directory="${render_directory}"/exports

		render_directory="${model_directory}"/renders

		flat_directory="${render_directory}"/flat

		thumbnail_directory="${render_directory}"/thumbnail

		# define model specific directories

		model_category=$(cat "${model_directory%/*}"/title)

		model_title=$(cat "${model_directory}"/title)

		model_title_string=$(echo ${model_title//\<\/\br\>/})

		model_paypal="${model_directory}"/paypal

		model_paypal_id=$(cat "${model_paypal}")

		model_pieces="${model_directory}"/pieces

		model_pieces_count=$(cat "${model_pieces}")

		model_instructions="${model_directory}"/instructions

		model_price="${model_directory}"/price

		model_instructions_price=$(cat "${model_price}")

		# generate model drawer entries

		if [[ -f "${model_directory}"/work-in-progress ]]
		then
			color="orange"
		else
			color="green"
		fi

cat << MODEL-DRAWER-CONTENT ->> "${modules_directory}"/drawer.html
		<div class="list section">

			<div class="flex flex-column flex-middle">

				<a class="container" href="/${model_directory}">

					<div class="flex flex-column flex-middle">

						<div class="flex-cell-start">

							<div class="icon icon-flex icon-center logo-${color}"></div>

						</div>

					</div>

					<div class="flex flex-column flex-middle">

						<div class="flex-cell">

							<img src="/${thumbnail_directory}/thumbnail.png"/>

						</div>

					</div>

					<div class="label flex flex-column flex-middle">

						<div class="flex-cell category">

							${model_category}

						</div>

						<div class="flex-cell text-center">

							${model_title}

						</div>

						<div class="flex-cell text-center">

							[ ${model_pieces_count} PIECES ]

						</div>

					</div>

				</a>

			</div>

		</div>

MODEL-DRAWER-CONTENT

	((count++))

	done
done

# generate footer

cat << MODEL-DRAWER-FOOTER ->> "${modules_directory}"/drawer.html
		<!-- copyright -->

		<div class="list section copyright">

			<div class="flex flex-column flex-stretch">

				<div class="flex-cell category">

					COPYRIGHT

				</div>

				<a class="container" href="https://nathaneltitane.com">

					<div class="flex flex-column flex-center flex-middle">

						<div class="flex">

							<div class="avatar avatar-128" href=""></div>

						</div>

					</div>

					<div class="flex flex-column flex-center flex-middle">

						<div class="flex-cell text-center">

							Version // ${stamp}</br>
							Lego // Linux - Where Lego meets Linux</br>
							N Λ T H Λ N E L - ©  <text id="year"></text>

						</div>

					</div>

				</a>

			</div>

		</div>

	</div>

</div>

MODEL-DRAWER-FOOTER

frobulator.inf "Models" "[ ${count} ]"
echo

frobulator.cpt "Complete" "[ Drawer ]"
echo
