#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	curl -s -L get.frbltr.app > /usr/bin/frobulator
fi

. /usr/bin/frobulator

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER}"
	HOME=/home/"${USER}"
fi

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="04-21-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << MODEL-DRAWER-HEADER -> "modules/drawer.html"

<!-- drawer -->

<div class="drawer">

	<div class="drawer-button cursor-cell"></div>

	<div class="drawer-container">

		<copyright>

		</copyright>

		<div class="grid grid-column grid-stretch">

MODEL-DRAWER-HEADER

# values

extensions_list=(
	png
)

for extension in ${extensions_list[@]}
do
	count=1

	# shuffle models directories list:
	# creates random showcase of all models on each update

	for models_directory in $(find models/ -type f -iname flat."${extension}" | sort)
	do
		IFS='/' read -r -a path <<< $(echo "$models_directory")

		# /models/model-type/model/renders/flat/flat.${extension}

		# "${path[0]}" /models
		# "${path[1]}" /model-category
		# "${path[2]}" /model
		# "${path[3]}" /renders
		# "${path[4]}" /outine
		# "${path[5]}" /flat

		model_category=$(cat ${path[0]}/${path[1]}/title)
		model_title=$(cat ${path[0]}/${path[1]}/${path[2]}/title)

# generate model drawer entries

cat << MODEL-DRAWER-CONTENT ->> "modules/drawer.html"
				<!-- BEGIN ENTRY -->

				<div class="grid-cell ">

					<a class="button title text-right cursor-pointer" href="models/${path[1]}/${path[2]}/" target="_blank">${model_category} // ${model_title}</a>

				</div>


				<!-- END ENTRY -->

MODEL-DRAWER-CONTENT

	((count++))

	done
done

# generate footer

cat << MODEL-DRAWER-FOOTER ->> "models/models-menu.html"
		</div>

	</div>

</div>

MODEL-DRAWER-FOOTER

frobulator.inf "Parsed model entries" "[ ${count} ]"
echo

frobulator.scs "Models drawer" "[ Done ]"
echo
