#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="03-09-2024"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

extension="mpd"

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

instructions () {

	extension="${1}"
	instructions_option="${2}"
	directory="${3}"

	"${SHELL}" ../l2cu/l2cu									\
					--file ${extension}						\
					--instructions ${instructions_option}	\
					--directory "${directory}"
}

# requirements /////////////////////////////////////////////////////////////////

if [[ -z "${directory}" ]]
then
    list+=(
        /media/internal/Lego/models
    )
else
    list+=(
        "${directory}"
    )
fi

instructions_options=(
	samples
)

for directory in ${list[@]}
do
	for instructions_option in ${instructions_options[@]}
	do
		instructions "${extension}" "${instructions_option}" "${directory}"
	done
done

list=()

frobulator.cpt "Complete" "[ Instructions ]"
echo
