#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2026-06-03"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

local_directory=/media/internal/Lego
local_models_directory="${local_directory}"/models

server_directory="${PWD}"
server_models_directory="${server_directory}"/models
server_images_directory="${server_directory}"/images
server_javascript_directory="${server_directory}"/javascript

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

synchronize () {

	source="${1}"
	destination="${2}"

	rsync				\
		--archive		\
		--quiet			\
		--recursive		\
						"${source}" "${destination}" > "${sink}" 2>&1

}

# background ///////////////////////////////////////////////////////////////////

# prepare update

frobulator.directory "${server_directory}" images

frobulator.fwd "Copying..."
echo

# values

extensions_list+=(
	png
)

for extension in ${extensions_list[@]}
do
	directories_list=(
		flat
		overlay
		social
		thumbnail
	)

	for directory in ${directories_list[@]}
	do
		frobulator.directory "${server_images_directory}" "${directory}"

		count=0

		# set IFS

		IFS=$'\n'

		# shuffle models directories list:
		# creates random showcase of all models on each update

		for image_path in $(find ${local_models_directory} -type f -not -path "work-in-progress" -iname "${directory}"."${extension}" | sort)
		do
			# get model directory

			model_directory="${image_path%/*/*/*}"

			if [ -f "${model_directory}"/background ]
			then

				image_count=$(printf "%03d" "${count}")

				# get model image base directory from path

				image_directory="${image_path%/*}"

				# get model image file name from path

				image_file="${image_path##*/}"

				# get model image file extension from path

				image_extension="${image_file##*.}"

				# strip extension from model file name

				image_name="${image_file%.*}"

				# set synchronization paths

				local_path="${image_path}"

				server_path="${server_images_directory}"/${directory}/${image_name}-"${image_count}"."${extension}"

				synchronize "${image_path}" "${server_path}"
			fi

			((count++))

		done

	done

	# reset IFS

	IFS=''

done

# update random background generator with new image file count

frobulator.inf "Updating" "[ Images ]"
echo

sed															\
	-i														\
	-e "s/var count = .*/var count = ${count};/g"		\
															"${server_javascript_directory}"/background.js

frobulator.inf "Models" "[ ${count} ]"
echo

frobulator.cpt "Complete" "[ Images ]"
echo
