#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2024-10-29"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

models_directory="${PWD}"/models
modules_directory="${PWD}"/modules

stamp=$(date +"%m-%d-%Y")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << MODEL-DRAWER-HEADER -> "${modules_directory}"/drawer.html
<!-- scripts -->

<script src="/javascript/drawer.js" type="text/javascript"></script>

<script src="/javascript/year.js" type="text/javascript"></script>

<!-- drawer -->

<div class="drawer">

	<div class="flex flex-column">

		<!-- notice -->

		<div class="section notice">

			<div class="flex flex-column section">

				<div class="flex-cell text-bold text-center">

					// NOTICE //</br>

					</br>

				</div>

				<div class="flex-cell text-center">

					INSTRUCTIONS ARE MADE AVAILABLE PROGRESSIVELY:</br>

					</br>

					PURCHASING AN INSTRUCTION SET PRIORITIZES AVAILABILITY FOR THAT MODEL!</br>

					</br>

					 YOU CAN <label for="modal-contact" class="modal-item contact cursor-pointer text-bold">// CONTACT //</label> US REGARDING ANY SPECIFIC MODEL, ANYTIME!</br>

					 </br>

				</div>

				<div class="flex-cell text-bold text-center">

					THANK YOU FOR YOUR SUPPORT!</br>

				</div>

			</div>

		</div>

		<!-- status available -->

		<div class="section status-available">

			<div class="flex flex-row flex-middle section">

				<div class="flex-cell-start">

					<div class="icon icon-flex icon-center logo-green"></div>

				</div>

				<div class="flex-cell text-right">

					MODEL INSTRUCTIONS AVAILABLE

				</div>

			</div>

		</div>

		<!-- status progress -->

		<div class="section status-progress">

			<div class="flex flex-row flex-middle section">

				<div class="flex-cell-start">

					<div class="icon icon-flex icon-center logo-orange"></div>

				</div>

				<div class="flex-cell text-right">

					MODEL INSTRUCTIONS WORK IS IN PROGRESS

				</div>

			</div>

		</div>

		<!-- models -->

		<div class="section models">

			<div class="grid grid-columns-responsive">

MODEL-DRAWER-HEADER

# values

extensions_list+=(
	dae
)

for extension in ${extensions_list[@]}
do
	count=1

	models_list=( $(find "${models_directory}" -type f -iname "work-in-progress*.${extension}" ! -iname "*instructions*" | sort) )

	models_list+=( $(find "${models_directory}" -type f -iname "*.${extension}" ! -iname "work-in-progress*" ! -iname "*instructions*"  | sort) )

	# set IFS

	IFS=$'\n'

	for model_path in ${models_list[@]}
	do
		model_path=$(echo "${model_path}" | cut -d '/' -f6-)

		# get model file name from path

		model_file="${model_path##*/}"

		# strip extension from model file name

		model_name="${model_file%.*}"

		# use model directory as root

		model_directory="${model_path%/*/*}"

		# define model output directories

		render_directory="${model_directory}"/renders

		export_directory="${render_directory}"/exports

		flat_directory="${render_directory}"/flat

		thumbnail_directory="${render_directory}"/thumbnail

		# define model specific directories

		model_category=$(cat "${model_directory%/*}"/title)

		model_drawer_entry="${model_directory}"/drawer

		model_title=$(cat "${model_directory}"/title)

		model_title_string=$(echo ${model_title//\<\/\br\>/})

		model_paypal="${model_directory}"/paypal

		model_paypal_id=$(cat "${model_paypal}")

		model_pieces="${model_directory}"/pieces

		model_pieces_count=$(cat "${model_pieces}")

		model_instructions="${model_directory}"/instructions

		model_price="${model_directory}"/price

		model_instructions_price=$(cat "${model_price}")

		# generate model drawer entries

		if [[ "${model_directory}" = *work-in-progress* ]]
		then
			color="yellow"

			marker="work-in-progress"

		elif [[ -f "${model_directory}"/work-in-progress ]]
		then
			color="orange"

			unset marker
		else
			color="green"

			unset marker
		fi

		if [[ -f "${model_directory}"/drawer ]]
		then

cat << MODEL-DRAWER-CONTENT ->> "${modules_directory}"/drawer.html

			<div class="flex flex-column">

				<div class="container ${marker}">

					<div class="flex flex-row flex-middle section">

						<div class="flex-cell-start">

							<div class="icon icon-flex icon-center logo-${color}"></div>

						</div>

						<div class="flex-cell label text-right">

							${model_title} </br> ${model_pieces_count} PIECES

						</div>

					</div>

					<a class="flex flex-column flex-middle" href="/${model_directory}">

						<div class="flex-cell">

							<img src="/${thumbnail_directory}/thumbnail.png"/>

						</div>

					</a>

				</div>

			</div>

MODEL-DRAWER-CONTENT

		fi

	((count++))

	done
done

# generate footer

cat << MODEL-DRAWER-FOOTER ->> "${modules_directory}"/drawer.html
			</div>

		</div>

		<!-- disclaimer -->

		<div class="section disclaimer">

			<div class="flex flex-column section">

				<div class="flex-cell text-bold text-center">

					// DISCLAIMER //</br>

					</br>

				</div>

				<div class="flex-cell text-bold text-center">

					LEGO® IS A TRADEMARK OF THE LEGO® GROUP OF COMPANIES</br>

					WHICH DOES NOT SPONSOR, AUTHORIZE OR ENDORSE THIS PROJECT</br>

					NOR THE PRODUCTS MADE AVAILABLE ON THIS WEBSITE.</br>

					</br>

				</div>

				<div class="flex-cell text-center">

					WHILE EVERY EFFORT IS MADE TO ENSURE ACCURACY,</br>

					SPECIFIC LEGO® ELEMENTS MAY VARY IN COLOR OR AVAILABILITY.</br>

					</br>

					 <div class="flex-cell text-bold text-center">

						// THE FINAL BUILD COLORS MAY DIFFER FROM THE INSTRUCTIONS PROVIDED! //</br>

					</div>

				</div>

			</div>

		</div>

		<!-- copyright -->

		<div class="section copyright">

			<div class="flex flex-column flex-stretch">

				<div class="flex-cell category text-center">

					COPYRIGHT

				</div>

				<a class="container" href="https://nathaneltitane.com">

					<div class="flex flex-column flex-center flex-middle">

						<div class="flex">

							<div class="avatar avatar-128" href=""></div>

						</div>

					</div>

					<div class="flex flex-column flex-center flex-middle">

						<div class="flex-cell text-center">

							Version // ${stamp}</br>
							Mecha // Blocks - Where LEGO® meets Open Source</br>
							N Λ T H Λ N E L - ©  <text id="year"></text>

						</div>

					</div>

				</a>

			</div>

		</div>

	</div>

</div>

MODEL-DRAWER-FOOTER

frobulator.inf "Models" "[ ${count} ]"
echo

frobulator.cpt "Complete" "[ Drawer ]"
echo
