#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ $(id -u -n) = "root" ]]
then
	SUDO_HOME=/root

	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

echo

echo "[  -  ] Checking..."
echo

if [[ -z $(command -v curl) ]]
then
	if [[ -n $(command -v apt-get) ]]
	then
		apt-get -q -q update > /dev/null 2>&1
		apt-get -q -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v dnf) ]]
	then
		dnf -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v yum) ]]
	then
		yum -q install -y curl > /dev/null 2>&1

	elif [[ -n $(command -v apk) ]]
	then
		apk add --quiet curl > /dev/null 2>&1

	elif [[ -n $(command -v pacman) ]]
	then
		pacman -S -y --noconfirm --noprogressbar curl > /dev/null 2>&1

	elif [[ -n $(command -v zypper) ]]
	then
		zypper --quiet --non-interactive install curl > /dev/null 2>&1
	fi
fi

if [[ -z $(command -v curl) ]]
then
	echo "[  !  ] Unable to install or binary not found /////////////////////// [ 'curl' ]"
	echo

	exit 1
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(	curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)

version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-01-01-1970}"

date_online="${version_online:6:4}${version_online:0:2}${version_online:3:2}"

date_local="${version_local:6:4}${version_local:0:2}${version_local:3:2}"

if [ ! -f "${frobulator}" ] ||
   [[ "${date_online}" > "${date_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

echo "[  >  ] Implementing..."
echo

source "${frobulator}"

# superuser ////////////////////////////////////////////////////////////////////

export self_arguments="${@}"

# frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

# version //////////////////////////////////////////////////////////////////////

version="2024-03-09"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

modules_directory="${PWD}"/modules

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << 'MODELS-MENU-HEADER' -> "${modules_directory}/"menu.html
		<script>

			$(function(){

				$.get("/modules/anchors.html", function (data) {

					$("#anchors").append(data);

				});

				}
			);

		</script>

		<!-- BEGIN MODELS MENU -->

MODELS-MENU-HEADER

# values

extensions_list+=(
	dae
)

for extension in ${extensions_list[@]}
do
	count=1

	models_list=( $(find "${models_directory}" -type f -iname "*.${extension}" ! -iname "*instructions*" | sort) )

	# set IFS

	IFS=$'\n'

	for model_path in ${models_list[@]}
	do
		model_path=$(echo "${model_path}" | cut -d '/' -f6-)

		# get model file name from path

		model_file="${model_path##*/}"

		# strip extension from model file name

		model_name="${model_file%.*}"

		# use model directory as root

		model_directory="${model_path%/*/*}"

		# define model output directories

		export_directory="${render_directory}"/exports

		render_directory="${model_directory}"/renders

		flat_directory="${render_directory}"/flat

		thumbnail_directory="${render_directory}"/thumbnail

		# define model specific directories

		model_category=$(cat "${model_directory%/*}"/title)

		model_title=$(cat "${model_directory}"/title)

		model_title_string=$(echo ${model_title//\<\/\br\>/})

		model_paypal="${model_directory}"/paypal

		model_paypal_id=$(cat "${model_paypal}")

		model_pieces="${model_directory}"/pieces

		model_pieces_count=$(cat "${model_pieces}")

		model_instructions="${model_directory}"/instructions

		model_price="${model_directory}"/price

		model_instructions_price=$(cat "${model_price}")

		# keep first container visible

		if [ "${count}" -eq 1 ]
		then
			hidden=""
		else
			hidden="hidden"
		fi

# generate model container

cat << MODEL-CONTAINER ->> "${modules_directory}/"menu.html
<!-- BEGIN CONTAINER -->

<div id=${model_title_string/ /-} class='container ${hidden}'>

	<div class='flex flex-column flex-center flex-around flex-wrap'>

		<div class='flex-cell'>

			<a href="models/${path[1]}/${path[2]}"'>

				<img src="/${path[0]}/${path[1]}/${path[2]}/${path[3]}/${path[4]}/${path[5]}"/>

			</a>

		</div>

	</div>

MODEL-CONTAINER

if [ -d "${model_instructions}" ]
then

cat << MODEL-TITLE ->> "${modules_directory}/"menu.html
	<div id="menu" class="menu section flex flex-column flex-stretch">

		<div class="category flex-cell text-left">

			${model_category}

		</div>

		<a class="container" href="models/${path[1]}/${path[2]}/">

			<div class="flex flex-row flex-middle">

				<div class="flex">

					<div class="icon icon-flex icon-center logo-green"></div>

				</div>

				<div class="flex-cell text-center">

					${model_title_string}

				</div>

			</div>

		</a>

	</div>

</div>

<!-- END CONTAINER -->

MODEL-TITLE

else

cat << MODEL-TITLE ->> "${modules_directory}/"menu.html
	<div id="menu" class="menu section flex flex-column flex-stretch">

		<div class="category flex-cell text-left">

			${model_category}

		</div>

		<a class="container" href="models/${path[1]}/${path[2]}/">

			<div class="flex flex-row flex-middle">

				<div class="flex">

					<div class="icon icon-flex icon-center logo-orange"></div>

				</div>

				<div class="flex-cell text-center">

					${model_title_string}

				</div>

			</div>

		</a>

	</div>

</div>

<!-- END CONTAINER -->

MODEL-TITLE

fi

	((count++))

	done
done

# generate footer

cat << FOOTER ->> "${modules_directory}/"menu.html
<!-- END MODELS MENU -->

<div id="anchors" class="section">

</div>

FOOTER

frobulator.inf "Models" "[ ${count} ]"
echo

frobulator.cpt "Complete" "[ Menu ]"
echo
