#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [ -f "${HOME}"/.local/bin/frobulator ]
then
	rm -r -f "${HOME}"/.local/bin/frobulator
fi

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="06-04-2026"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

site_url='https://mechablocks.com'

output_file='sitemap.xml'

site_url="${site_url%/}"

# defaults /////////////////////////////////////////////////////////////////////

page_count=0

# functions ////////////////////////////////////////////////////////////////////

url_crawl () {

	local url_path="${1}"
	local file_path="${2}"
	local modified_date

	url_path="${url_path#./}"
	url_path="${url_path#index.html}"
	url_path="${url_path%index.html}"
	url_path="${url_path%/}"

	if [ "${url_path}" = "." ] ||
	   [ "${url_path}" = ""  ]
	then
		url_path="/"
	else
		url_path="/${url_path}/"
	fi

	url_path="${url_path//\/\//\/}"

	date_modified="$(date -u -r "${file_path}" '+%Y-%m-%d')"

	frequency_change="weekly"

	cat >> "${output_file}" << URL

	<url>

		<loc>${site_url}${url_path}</loc>

		<lastmod>${date_modified}</lastmod>

		<changefreq>${frequency_change}</changefreq>

		<priority>0.80</priority>

	</url>
URL

	(( page_count++ ))

}

# initialize ///////////////////////////////////////////////////////////////////

if [ -f './sitemap.xml' ]
then
	rm				\
		--recursive	\
		--force		\
					'./sitemap.xml'
fi

# sitemap - header

cat >> "${output_file}" << HEADER
<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
HEADER

# write homepage

if [ -f './index.html' ]
then
	url_crawl './index.html' './index.html'
fi

# crawl index pages

while IFS= read -r file_path
do
	if [ "${file_path}" = './index.html' ] ||
	   [[ "${file_path}" == ./modules/* ]] ||
	   [[ "${file_path}" == ./logo/*    ]] ||
	   [[ "${file_path}" == ./assets/*  ]] ||
	   [[ "${file_path}" == ./images/*  ]] ||
	   [[ "${file_path}" == ./renders/* ]]
	then
		continue
	fi

	# write index pages

	url_crawl "${file_path}" "${file_path}"

done < <( find . -type f -name 'index.html' | sort )

# crawl model folders

if [ -d './models' ]
then
	while IFS= read -r directory_path
	do
		if [ -f "${directory_path}/index.html" ]
		then
			continue
		fi

		if [ -f "${directory_path}/model.dae"        ] ||
		   [ -f "${directory_path}/model.glb"        ] ||
		   [ -f "${directory_path}/model.gltf"       ] ||
		   [ -f "${directory_path}/instructions.pdf" ] ||
		   [ -d "${directory_path}/renders"          ]
		then

			# write model directory urls

			url_crawl "${directory_path}" "${directory_path}"
		fi

	done < <( find ./models -mindepth 2 -maxdepth 2 -type d | sort )
fi

# write footer

cat >> "${output_file}" << FOOTER

</urlset>
FOOTER

# report

if [ "${page_count}" -eq 0 ]
then
	frobulator.err "No URLs found" "[ '${site_url}' ]"
	echo

	frobulator.wrn "Script must be run from site root directory."
	echo
else
	frobulator.inf "Sitemap written" "[ ${output_file} ]"
	echo

	frobulator.inf "URL count" "[ ${page_count} ]"
	echo

	frobulator.cpt "Complete" "[ Sitemap ]"
fi
